config/routes.rb
Rails.application.routes.draw do
  resources :products do
  end

  resource :cart, only:[:show, :destroy] do
    collection do
      post :add, path:'add/:id'
      get :mpg, path: 'checkout'
      post :notify
      post :return
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :find_product, only: [:edit, :update, :destroy,  :checkout]

    def index
      @products = Product.all
    end
  
    def show
      @product = Product.find_by(id: params[:id])
    end

    def new
      @product = Product.new
    end
  
    def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to products_path, notice: "新增商品完成"
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @product.update(product_params)
        redirect_to products_path, notice: "商品更新成功"
      else
        render :edit
      end
    end
  
    def destroy
      @product.destroy
      redirect_to products_path, notice: "商品已刪除"
    end

  
  
    private
    def find_product
      @product = Product.find_by(id: params[:id])
      redirect_to products_path, notice: "無此商品" unless @product
    end
  
    def product_params
      params.require(:product).permit(:title, :description, :price)
    end


end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for (@product) do |f| %>
  <%= f.text_field :title, placeholder: "商品名稱" %>
  <%= f.text_field :description, placeholder: "說明" %>
  <%= f.text_field :price, placeholder: "售價" %>
  <%= f.submit "新增書本", class: "btn btn-default btn-primary" %>
<% end %>

app/views/products/edit.html.erb
<h1>編輯商品</h1>

<%= render "form", product: @product %>

 

app/views/products/index.html.erb
<h1>商品列表</h1>

<%= link_to '新增商品', new_product_path, class: "btn btn-default btn-primary" %>
<%= link_to '購物車', cart_path, class: "btn btn-default btn-success" %>

<table class="table">
  <thead>
    <tr>
      <td>商品名稱</td>
      <td>售價</td>
      <td>處理</td>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td>
        <%= link_to '放到購物車', add_cart_path(product), method: "post", class: "btn btn-xs btn-danger" %>
        <%= product.title %>
      </td>
      <td><%= product.price %></td>
      <td>
        <%= link_to '編輯', edit_product_path(product), class: "btn btn-xs btn-default" %>
        <%= link_to '刪除', product, method: "delete", data: { confirm: "確定刪除?" }, class: "btn btn-xs btn-default" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>新增商品</h1>

<%= render "form", product: @product %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Back', products_path, class:'btn btn-default' %>
<hr />

<%= form_for(@product, url: mpg_products_path(@product), method: :post) do |f| %>

  <div id="payment-form"></div>
  <%= f.submit "確認付款", class:"btn btn-default btn-danger" %>
<% end %>